//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: google/datastore/v1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf



// Provides conformance to `GRPCPayload`
extension Google_Datastore_V1_EntityResult: GRPCProtobufPayload {}
extension Google_Datastore_V1_Query: GRPCProtobufPayload {}
extension Google_Datastore_V1_KindExpression: GRPCProtobufPayload {}
extension Google_Datastore_V1_PropertyReference: GRPCProtobufPayload {}
extension Google_Datastore_V1_Projection: GRPCProtobufPayload {}
extension Google_Datastore_V1_PropertyOrder: GRPCProtobufPayload {}
extension Google_Datastore_V1_Filter: GRPCProtobufPayload {}
extension Google_Datastore_V1_CompositeFilter: GRPCProtobufPayload {}
extension Google_Datastore_V1_PropertyFilter: GRPCProtobufPayload {}
extension Google_Datastore_V1_GqlQuery: GRPCProtobufPayload {}
//extension Google_Datastore_V1_GqlQuery.NamedBindingsEntry: GRPCProtobufPayload {}
extension Google_Datastore_V1_GqlQueryParameter: GRPCProtobufPayload {}
extension Google_Datastore_V1_QueryResultBatch: GRPCProtobufPayload {}
