name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        key: SPM-${{ runner.os }}
        path: .build/
    - name: Build
      run: swift build -v

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        key: SPM-${{ runner.os }}
        path: .build/
    - name: Build
      run: swift build -v

  # Tests currently requires the gcloud datastore emulator
  #test:
  #  runs-on: macos-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Run tests
  #    run: swift test -v
